name: dutch_game_studio_game
description: "A new Flutter project."
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  flutter_bloc: ^9.0.0
  restart_app: ^1.3.2
  universal_html: ^2.2.4

flutter:
  assets:
    - assets/images/ 

